# tyro YAML.
!dataclass:TrainingConfig
batch_size: 1024
initialization: encoder
method: !dataclass:GeometryGuidedLangevin
  beta1: 0.9
  beta2: 0.999
  learning_rate: 0.05
  loss: !dataclass:GeometricLoss
    eikonal_sigma: 0.01
    eikonal_weight: 0.01
    num_siren_points: 5000
    num_surface_points: 1024
    num_uniform_points: 500
    sdf_weight: 1.0
    siren_alpha: 50
    siren_weight: 0.0
  noise_step: 1
  optimizer: adam
  scale_lr: false
  sigma: 0.2
  sigma_min: 0.02
  sigma_schedule: cos
  sigma_schedule_max: 4000
n_steps: 5000
random_seed: 42
output_dir: !!python/object/apply:pathlib.PosixPath
- .
pointcloud_path: !!python/object/apply:pathlib.PosixPath
- .
model_path: !!python/object/apply:pathlib.PosixPath
- .
autoencoder_path: !!python/object/apply:pathlib.PosixPath
- .